name: CI Java App

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  call-workflow-local:
    uses: relari/ci-templates/.github/workflows/template-local.yml@main
    with:
      java-version: '17'
#      maven-goal: 'verify'          # incluye pruebas
      run-tests: false
      app-port: '8081'
      postman-collection: './_postman/API_EMPLOYEE_DEVOPS.postman_collection.json'