name: Build and Deploy Locally

on:
  push:
    branches: [ disabled ]
  pull_request:
  workflow_dispatch:

jobs:
  call-template-build-deploy-local:
    uses: relari/ci-templates/.github/workflows/template-build-deploy-local.yml@main
    with:
      component-name: 'api-employee-devops'
      java-version: '17'
      project-type: 'maven'
      app-port: '8081'
      base-url: 'http://localhost:8081'
      postman-collection: './_postman/API_EMPLOYEE_DEVOPS.postman_collection.json'