name: Build and Test with Sonar

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  call-template-build-and-test:
    uses: relari/ci-templates/.github/workflows/template-build-and-test.yml@main
    with:
      component-name: 'api-employee-devops'
      java-version: '17'
      project-type: 'maven'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_USERNAME: ${{ secrets.SONAR_USERNAME }}
