name: Build Repo

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  call-template-build-repo:
    uses: relari/ci-templates/.github/workflows/template-build-repo.yml@main
    with:
      component-name: 'api-employee-devops'
      java-version: '17'
      project-type: 'maven'
      app-port: '8081'
      base-url: 'http://localhost:8081'
      postman-collection: './_postman/API_EMPLOYEE_DEVOPS.postman_collection.json'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_USERNAME: ${{ secrets.SONAR_USERNAME }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
