name: Build and Deploy Locally

on:
  push:
    branches: [ disable-local-deploy ]
  pull_request:
  workflow_dispatch:

jobs:
  call-template-build-deploy-local:
    uses: relari/ci-templates/.github/workflows/template-build-deploy-local.yml@main
    with:
      java-version: '17'
      app-port: '8081'
      postman-collection: './_postman/API_EMPLOYEE_DEVOPS.postman_collection.json'